services:
  data_generator:
    env_file:
      - ".env"
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '2gb'
    shm_size: '2gb'
    image: "building-damage-visualizer:latest"
    environment:
      - DEFAULT_CONDA_ENV_NAME=${conda_env_name}
      - APP_DIR=${app_dir}
      - APP_PORT=${app_port}
    command:
      - /bin/bash
      - -c
      - |
        cd $${app_dir}
        python -c 'import os;print(os.getcwd());'
        python create_outputs.py --pre-imagery  $${app_data_dir}/$${pre_imagery_file_name} --post-imagery  $${app_data_dir}/$${post_imagery_file_name} --name $${imagery_output_file_name} --output-dir $${app_data_dir}
    volumes:
      - type: bind
        source: ${local_data_dir}
        target: "${app_data_dir}"